server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-store-password: mypassword
    key-alias: mykey

spring:
#  jpa:
#    properties:
#      hibernate:
#        default_schema: public
#        hbm2ddl:
#          auto: update


  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: false
      lifecycle-management: start_only

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/samurai
    username: samurai
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public